<#
.SYNOPSIS
    End-to-end test for the Phase 7 alert pipeline.

.DESCRIPTION
    Imports a synthetic finding into Security Hub and waits for the alert
    Lambda to log it, exercising the real path:

        BatchImportFindings -> Security Hub -> EventBridge -> Lambda -> Logs

    Why not `aws events put-events`?

    EventBridge rejects any custom event whose source begins with "aws." -
    reserved for AWS services. A hand-crafted "aws.securityhub" event cannot be
    injected onto the bus, so put-events can only test a rule this pipeline
    does not use. BatchImportFindings is the supported way to get a genuine
    Security Hub finding event onto the default bus, and it exercises the
    actual event pattern rather than an approximation of it.

    The finding is archived on completion so a synthetic CRITICAL does not sit
    in the Security Hub dashboard afterwards. Pass -KeepFinding to leave it.

.PARAMETER Severity
    Severity label to import. Use a low label to verify the rule does NOT fire.

.PARAMETER TimeoutSeconds
    How long to wait for the alert to appear in CloudWatch Logs.

.EXAMPLE
    ./test-high-severity-alert.ps1
    Imports a HIGH finding and expects an alert.

.EXAMPLE
    ./test-high-severity-alert.ps1 -Severity LOW -ExpectNoAlert
    Negative test: proves the rule filters rather than passing everything.
#>

[CmdletBinding()]
param(
    [ValidateSet('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')]
    [string]$Severity = 'HIGH',

    [string]$FunctionName = 'cloudsec-lab-securityhub-alert',

    [switch]$ExpectNoAlert,
    [switch]$KeepFinding,

    [int]$TimeoutSeconds = 120
)

$ErrorActionPreference = 'Stop'

function Write-Step($Message) { Write-Host "`n==> $Message" -ForegroundColor Cyan }
function Write-Pass($Message) { Write-Host "    PASS  $Message" -ForegroundColor Green }
function Write-Fail($Message) { Write-Host "    FAIL  $Message" -ForegroundColor Red }
function Write-Info($Message) { Write-Host "    $Message" -ForegroundColor DarkGray }

# --- Context -----------------------------------------------------------------

Write-Step 'Resolving account context'

$identity = aws sts get-caller-identity --output json | ConvertFrom-Json
$accountId = $identity.Account
$region = aws configure get region
if ([string]::IsNullOrWhiteSpace($region)) { $region = 'us-east-1' }

Write-Info "account=$accountId region=$region"

$logGroup = "/aws/lambda/$FunctionName"

# The account's default product ARN. Findings imported under this ARN are
# treated as first-party findings from this account, which is what a custom
# detection integrating with Security Hub would use.
$productArn = "arn:aws:securityhub:${region}:${accountId}:product/${accountId}/default"

# Unique per run, so repeated runs are separate findings rather than updates to
# one finding - an update would re-publish with Workflow.Status unchanged and
# muddy the result.
$findingId = "lab-phase7-selftest-$([guid]::NewGuid().ToString('N').Substring(0,12))"
$now = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffZ')

# --- Build the finding -------------------------------------------------------

Write-Step "Importing synthetic $Severity finding"

$finding = @{
    SchemaVersion = '2018-10-08'
    Id            = $findingId
    ProductArn    = $productArn
    GeneratorId   = 'cloudsec-lab/phase-7/self-test'
    AwsAccountId  = $accountId
    Region        = $region
    Types         = @('Software and Configuration Checks/Lab/SelfTest')
    CreatedAt     = $now
    UpdatedAt     = $now
    Severity      = @{ Label = $Severity }
    Title         = "SYNTHETIC LAB FINDING - Phase 7 pipeline self-test ($Severity)"
    Description   = 'Generated by detections/test-high-severity-alert.ps1 to verify the Security Hub -> EventBridge -> Lambda path. Not a real security finding.'
    RecordState   = 'ACTIVE'
    Workflow      = @{ Status = 'NEW' }
    Resources     = @(
        @{
            Type      = 'Other'
            Id        = "arn:aws:securityhub:${region}:${accountId}:lab/synthetic-test-resource"
            Partition = 'aws'
            Region    = $region
        }
    )
}

# Written to a file rather than passed inline: quoting nested JSON through
# PowerShell into the AWS CLI on Windows is a reliable source of silent
# malformation.
#
# NOT written via Set-Content -Encoding utf8: on Windows PowerShell 5.1 that
# encoding emits a UTF-8 byte-order mark. The AWS CLI decides file:// content
# is JSON by checking whether it starts with '{' or '['; a BOM in front of
# that character makes it fall back to shorthand (key=value) parsing and fail
# with a misleading "Expected: '='" error. WriteAllText with a BOM-less
# UTF8Encoding avoids it.
$tempFile = Join-Path $env:TEMP "phase7-finding-$findingId.json"
$findingJson = ConvertTo-Json -InputObject @($finding) -Depth 10
[System.IO.File]::WriteAllText($tempFile, $findingJson, (New-Object System.Text.UTF8Encoding($false)))

# Marker for the log search. Anything logged before this instant belongs to an
# earlier run.
$startedAtMs = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()

try {
    $importJson = aws securityhub batch-import-findings --findings "file://$tempFile" --output json

    # Checked BEFORE parsing. A failed CLI call (bad credentials, malformed
    # JSON, throttling) leaves $importJson empty or full of error text, not
    # valid JSON. Piping that into ConvertFrom-Json produces $import = $null,
    # and PowerShell evaluates `$null.FailedCount -gt 0` as $false - so
    # skipping this check would print "PASS imported" for a call that never
    # imported anything.
    if ($LASTEXITCODE -ne 0) {
        Write-Fail "aws securityhub batch-import-findings failed (exit $LASTEXITCODE):"
        Write-Host $importJson
        exit 1
    }

    $import = $importJson | ConvertFrom-Json

    if ($import.FailedCount -gt 0) {
        Write-Fail "Security Hub rejected the finding: $($import.FailedFindings | ConvertTo-Json -Compress)"
        exit 1
    }

    Write-Pass "imported id=$findingId"
}
finally {
    Remove-Item $tempFile -ErrorAction SilentlyContinue
}

# --- Wait for the alert ------------------------------------------------------

Write-Step 'Waiting for the alert Lambda'
Write-Info "log group: $logGroup"

$deadline = (Get-Date).AddSeconds($TimeoutSeconds)
$found = $null

while ((Get-Date) -lt $deadline) {
    # The log group may not exist yet if the function has never been invoked.
    try {
        # The filter pattern needs a literal embedded double-quote on each
        # side for CloudWatch to treat this as one exact phrase rather than
        # three independently-required terms. PowerShell silently drops a
        # backtick-escaped or single-quoted `"..."` when it hands the
        # argument to a native exe - `aws --debug` confirms the API actually
        # receives the pattern with no quotes at all unless they're escaped
        # as \" here, which survives the PowerShell-to-argv boundary intact.
        # This one happens to still work either way, since the message
        # contains all three words regardless of match mode - the
        # Where-Object re-check below is what actually makes that safe to
        # rely on; see detections/test-automated-containment.ps1 for a
        # search term (a hyphenated finding ID) where the unescaped version
        # silently matched nothing.
        $eventsJson = aws logs filter-log-events `
            --log-group-name $logGroup `
            --start-time $startedAtMs `
            --filter-pattern '\"SECURITY INCIDENT DETECTED\"' `
            --output json 2>$null

        if ($LASTEXITCODE -eq 0 -and $eventsJson) {
            $events = @(($eventsJson | ConvertFrom-Json).events)
            $match = @($events | Where-Object { $_.message -like "*$findingId*" -or $_.message -like "*$Severity*" })

            if ($match.Count -gt 0) {
                $found = $match[0]
                break
            }
        }
    }
    catch {
        # Group not created yet; keep waiting.
    }

    Start-Sleep -Seconds 5
    Write-Host '.' -NoNewline -ForegroundColor DarkGray
}

Write-Host ''

# --- Verdict -----------------------------------------------------------------

Write-Step 'Result'

$exitCode = 0

if ($ExpectNoAlert) {
    if ($null -eq $found) {
        Write-Pass "no alert for $Severity - the rule filters as intended"
    }
    else {
        Write-Fail "$Severity produced an alert; the event pattern is too broad"
        Write-Host $found.message
        $exitCode = 1
    }
}
else {
    if ($null -ne $found) {
        Write-Pass "alert logged for $Severity"
        Write-Host ''
        Write-Host $found.message -ForegroundColor Yellow
    }
    else {
        Write-Fail "no alert within ${TimeoutSeconds}s"
        Write-Host ''
        Write-Info 'Check, in order:'
        Write-Info "  1. rule matched      aws cloudwatch get-metric-statistics --namespace AWS/Events --metric-name TriggeredRules ..."
        Write-Info "  2. lambda invoked    aws logs tail $logGroup --since 10m"
        Write-Info "  3. delivery failed   aws sqs receive-message --queue-url <dlq_url>"
        $exitCode = 1
    }
}

# --- Cleanup -----------------------------------------------------------------

if (-not $KeepFinding) {
    Write-Step 'Archiving the synthetic finding'

    # RecordState is NOT a batch-update-findings parameter - the CLI has no
    # --record-state option there, only Workflow.Status, Note, Severity, etc.
    # For a custom/third-party finding, RecordState is only ever set through
    # batch-import-findings, so archiving means re-importing the same
    # Id/ProductArn with RecordState=ARCHIVED. This re-publishes the finding to
    # EventBridge with that state, which the rule's RecordState filter drops -
    # if a second alert appears after this step, that filter is not working.
    $archiveFinding = $finding.Clone()
    $archiveFinding.RecordState = 'ARCHIVED'
    $archiveFinding.Workflow = @{ Status = 'RESOLVED' }
    $archiveFinding.UpdatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffZ')
    $archiveFinding.Note = @{
        Text      = 'Archived by the Phase 7 self-test (detections/test-high-severity-alert.ps1).'
        UpdatedBy = 'phase7-selftest'
        UpdatedAt = $archiveFinding.UpdatedAt
    }

    $archiveFile = Join-Path $env:TEMP "phase7-finding-$findingId-archive.json"
    $archiveJson = ConvertTo-Json -InputObject @($archiveFinding) -Depth 10
    [System.IO.File]::WriteAllText($archiveFile, $archiveJson, (New-Object System.Text.UTF8Encoding($false)))

    try {
        $archiveResultJson = aws securityhub batch-import-findings --findings "file://$archiveFile" --output json

        if ($LASTEXITCODE -eq 0) {
            $archiveResult = $archiveResultJson | ConvertFrom-Json
            if ($archiveResult.FailedCount -gt 0) {
                Write-Fail "archive rejected: $($archiveResult.FailedFindings | ConvertTo-Json -Compress)"
            }
            else {
                Write-Pass 'archived'
            }
        }
        else {
            Write-Fail "archive failed (exit $LASTEXITCODE) - remove $findingId manually"
            Write-Host $archiveResultJson
        }
    }
    finally {
        Remove-Item $archiveFile -ErrorAction SilentlyContinue
    }
}
else {
    Write-Info "finding left ACTIVE: $findingId"
}

exit $exitCode
